version: '3.5'
services:
  coffee-shop:
    image: ttlinh/coffee-shop
    container_name: coffee-shop
    restart: unless-stopped
    ports:
      - "6005:6005"
    environment:
      - "SPRING_DATASOURCE_URL=http://coffee-shop-db/coffee-shop-db"
    networks:
      - shop-network
    depends_on:
      - coffee-shop-db

  coffee-shop-db:
    image: postgres:14
    container_name: coffee-shop-db
    restart: unless-stopped
    ports:
      - "6001:5432"
    environment:
      POSTGRES_DB: coffee-shop-db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 123456
    networks:
      - shop-network

# Services on the same network can communicate with each other.
networks:
  shop-network:
    driver: bridge
