server.port: 9001

spring:
  datasource:
    url: jdbc:h2:mem:coffee-shop
    username: testuser
    password: 123456
    driverClassName: org.h2.Driver
    flyway:
      locations:
        - classpath:db/migration/schema
  h2:
    console.enabled: true
  jpa:
    generate-ddl: off
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true