server.port: 6005
spring:
  datasource:
    url:
    username: testuser
    password: 123456
  flyway:
    locations:
      - classpath:db/migration/schema
      - classpath:db/migration/data
  jpa:
    pa:
      generate-ddl: off
      hibernate.ddl-auto: none
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      show-sql: false
      properties:
        hibernate:
          jdbc.batch_size: 20
          format_sql: false
          show_sql: false
springdoc:
  enable-data-rest: false
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    doc-expansion: none
    path: /swagger-ui